web security set to false
This is needed to temporarily bypass the cross browser origin error of Cypress. Happens due to clicking of Get Started button and redirecting to the new url which doesn't match the origin policy of the previous url.

CypressError: Cypress detected a cross origin error happened
on page load: